[package]
name = "monty-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "monty"
path = "src/main.rs"

[dependencies]
monty = { path = "../monty" }
monty_type_checking = { path = "../monty-type-checking" }

[lints]
workspace = true
